version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    ports:
      - 32400:32400
    volumes:
      - /mediaserver/plex/library:/config
      - /mediaserver/plex/series:/tv  
      - /mediaserver/plex/peliculas:/movies
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mediaserver/sonarr/data:/config
      - /mediaserver/sonarr/tvseries:/tv
      - /mediaserver/sonarr/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=GB
    volumes:
      - /mediaserver/radarr/data:/config
      - /mediaserver/radarr/movies:/movies 
      - /mediaserver/radarr/downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=GB
    volumes:
      - /mediaserver/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped